<html>
	<head>
	<title> Trombinoscope  master 2 THYP </title>
	</head>
	<body>

	<?php
			$url = "https://picasaweb.google.com/data/feed/base/user/107401320610499259896/albumid/6065229773950541889?alt=rss&kind=photo&authkey=Gv1sRgCNak7e60l-7VlgE&hl=fr";
			$xml = simplexml_load_file($url);
			echo "<center>";
			echo "<table border ='10'>";
			if(isset($xml->channel->item))
			{
				echo "<h1>Trombinoscope  master 2 THYP</h1>";
			foreach ($xml->channel->item as $photo){
				echo "<tr>";
				echo "<td><p>===================================></p></td><td><img width='300px' src='".$photo->enclosure["url"]."'/><br/><p align='center'>".$photo->title."</p></td><td><p><===================================</p></td>";
				 echo"</tr>";				
			}
			}
			echo "</table>";
			echo "<center>";
		
	?>
	</body>
</html>